# Generated by Django 3.2.7 on 2021-09-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('office_num', models.IntegerField()),
                ('user_pass', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('hobby', models.CharField(blank=True, choices=[('0', 'cricket'), ('1', 'hocky'), ('2', 'Basket_boll'), ('3', 'Other')], default=3, max_length=1, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('country', models.CharField(blank=True, choices=[('0', 'INDIA'), ('1', 'USA'), ('2', 'UK'), ('3', 'Other')], default=3, max_length=1, null=True)),
                ('state', models.CharField(blank=True, choices=[('0', 'gujrat'), ('1', 'maharastra'), ('2', 'up'), ('3', 'Other')], default=3, max_length=1, null=True)),
                ('city', models.CharField(blank=True, choices=[('0', 'surat'), ('1', 'vadodra'), ('2', 'rajkot'), ('3', 'Other')], default=3, max_length=1, null=True)),
                ('collage', models.CharField(blank=True, choices=[('0', 'collage1'), ('1', 'collage2'), ('2', 'collage3'), ('3', 'Other')], default=3, max_length=1, null=True)),
                ('refrance', models.CharField(blank=True, choices=[('0', 'sociale_media'), ('1', 'office'), ('2', 'Other')], default=3, max_length=1, null=True)),
                ('joine_date', models.DateField()),
                ('markshit_12', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
