# Generated by Django 3.2.7 on 2021-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='hobby',
            field=models.CharField(blank=True, choices=[('0', 'cricket'), ('1', 'hocky'), ('2', 'Basket_boll'), ('3', 'Other')], default=3, max_length=255, null=True),
        ),
    ]
