# Generated by Django 3.2.7 on 2021-09-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0003_auto_20210922_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='city',
            field=models.IntegerField(blank=True, choices=[('0', 'surat'), ('1', 'vadodra'), ('2', 'rajkot'), ('3', 'Other')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='collage',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='country',
            field=models.IntegerField(blank=True, choices=[('0', 'INDIA'), ('1', 'USA'), ('2', 'UK'), ('3', 'Other')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='frist_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('0', 'Male'), ('1', 'Female')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='office_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='phone_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='refrance',
            field=models.CharField(blank=True, choices=[('0', 'sociale_media'), ('1', 'office'), ('2', 'Other')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='state',
            field=models.IntegerField(blank=True, choices=[('0', 'gujrat'), ('1', 'maharastra'), ('2', 'up'), ('3', 'Other')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='user_pass',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
