# Generated by Django 3.2.7 on 2021-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0004_auto_20210922_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='hobby',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
