# Generated by Django 3.2.7 on 2021-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0005_alter_stu_data_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='hobby',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
