# Generated by Django 3.2.7 on 2021-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0007_auto_20210922_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='office_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='phone_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
