# Generated by Django 3.2.7 on 2021-09-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0008_auto_20210923_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='joine_date',
            field=models.DateField(default=None),
        ),
    ]
