# Generated by Django 3.2.7 on 2021-09-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0009_alter_stu_data_joine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='joine_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
