# Generated by Django 3.2.7 on 2021-09-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0011_stu_data_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stu_data',
            old_name='address',
            new_name='Address',
        ),
    ]
