# Generated by Django 3.2.7 on 2021-09-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrastion', '0013_stu_data_user_pass2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='markshit_12',
            field=models.ImageField(blank=True, default=3, null=True, upload_to=None),
        ),
    ]
